//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _SWCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.Agendas = new HashSet<Agenda>();
            this.Deals = new HashSet<Deal>();
            this.GeneralSettings = new HashSet<GeneralSetting>();
            this.Sales = new HashSet<Sale>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int ContactId { get; set; }
        public string NameSurname { get; set; }
        public string CompanyName { get; set; }
        public string Position { get; set; }
        public Nullable<int> RecordTypeId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> NumberOfEmployeesId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> SingUpId { get; set; }
        public Nullable<int> GenderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agendas { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual NumberOfEmployee NumberOfEmployee { get; set; }
        public virtual RecordType RecordType { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual SingUp SingUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralSetting> GeneralSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
