//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _SWCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int EmployeeId { get; set; }
        public string NameSurname { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string DateOfBirth { get; set; }
        public string Position { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string DateOfEmployment { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> WorkingStatusId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Situation Situation { get; set; }
        public virtual WorkingSituation WorkingSituation { get; set; }
    }
}
