//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _SWCRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWCRMEntities : DbContext
    {
        public SWCRMEntities()
            : base("name=SWCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenda> Agendas { get; set; }
        public virtual DbSet<AgendaStatu> AgendaStatus { get; set; }
        public virtual DbSet<AgendaType> AgendaTypes { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Deal> Deals { get; set; }
        public virtual DbSet<DealStatu> DealStatus { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GeneralSetting> GeneralSettings { get; set; }
        public virtual DbSet<ImportanceLevel> ImportanceLevels { get; set; }
        public virtual DbSet<NumberOfEmployee> NumberOfEmployees { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RecordType> RecordTypes { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<SingUp> SingUps { get; set; }
        public virtual DbSet<Situation> Situations { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<WorkingSituation> WorkingSituations { get; set; }
    }
}
