//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _SWCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SalesId { get; set; }
        public string SalesName { get; set; }
        public string SalesDate { get; set; }
        public string SalesType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> SingUpId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual SingUp SingUp { get; set; }
    }
}
